#!/data/data/com.termux/files/usr/bin/bash
mkdir -p binds
folder=termux-fs/data/data/com.termux/files
if [ -d "$folder" ]; then
    first=1
    echo "skipping downloading"
fi
if [ "$first" != 1 ];then
    if [ ! -f "bootstrap.zip" ]; then
        echo "downloading bootstrap package"
        wget https://termux.net/bootstrap/bootstrap-`dpkg --print-architecture`.zip -O bootstrap.zip
    fi
    cur=`pwd`
    mkdir -p $folder/usr
    cd $folder/usr
    echo "decompressing bootstrap image image"
    unzip $cur/bootstrap.zip
    while read p; do
        echo "creating symlink for $p"
        ln -s ${p/←/ }
    done <SYMLINKS.txt
    rm SYMLINKS.txt
    for f in bin libexec lib/apt/methods;do
        echo "making files in $f executable"
        chmod -R 700 $f/*
    done
    cd $cur
    mkdir -p $folder/home
fi
ff=/data/data/com.termux/files
bin=start.sh
echo "writing launch script"

cat > $bin <<- EOM
#!/bin/bash
cd \$(dirname \$0)
command="proot"
command+=" -r termux-fs"
command+=" -b /system"
command+=" -b /dev/"
command+=" -b /sys/"
command+=" -b /etc/"
command+=" -b /proc/"
if [ -n "\$(ls -A binds)" ]; then
    for f in binds/* ;do
        . \$f
    done
fi
command+=" -w /data/data/com.termux/files/home/"
command+=" $ff/usr/bin/env -i"
command+=" HOME=$ff/home"
command+=" PATH=$ff/usr/bin:$ff/usr/bin/applets"
command+=" TERM=\$TERM"
command+=" ANDROID_DATA=/data"
command+=" ANDROID_ROOT=/system"
command+=" EXTERNAL_STORAGE=/sdcard"
command+=" LANG=\$LANG"
command+=" LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib"
command+=" PREFIX=/data/data/com.termux/files/usr"
command+=" TMPDIR=/data/data/com.termux/files/usr/tmp"
com="\$@"
if [ -L "$folder/home/.termux/shell" ];then
    shell=$ff/home/.termux/shell
    shellname=\`basename \$(readlink $folder/home/.termux/shell)\`
else
    shell=$ff/usr/bin/bash
    shellname=bash
fi
if [ -z "\$1" ];then
    exec \$command bash -c "exec -a -\$shellname \$shell"
else
    exec \$command sh -c "\$com"
fi
EOM
echo "fixing shebang of $bin"
termux-fix-shebang $bin
echo "making $bin executable"
chmod +x $bin
