#!/data/data/com.termux/files/usr/bin/bash
function comment(){
    echo -en "\e[45m"
    echo -n $@
    echo -e "\e[0m"
}
folder=$HOME/termux/data/data/com.termux/files
if [ -d "$folder" ]; then
    first=1
    comment "skipping downloading"
fi
if [ "$first" != 1 ];then
    if [ ! -f "bootstrap.zip" ]; then
        comment "downloading bootstrap package"
        wget https://termux.net/bootstrap/bootstrap-`dpkg --print-architecture`.zip -O bootstrap.zip
    fi
    cur=`pwd`
    mkdir -p $folder/usr
    cd $folder/usr
    comment "decompressing bootstrap image image"
    unzip $cur/bootstrap.zip
    while read p; do
        comment "creating symlink for $p"
        ln -s ${p/←/ }
    done <SYMLINKS.txt
    rm SYMLINKS.txt
    for f in bin libexec lib/apt/methods;do
        comment "making files in $f executable"
        chmod -R 700 $f/*
    done
    #comment "fixing nameserver, otherwise it can't connect to the internet"
    #echo "nameserver 8.8.8.8" > $folder/etc/resolv.conf
    mkdir $folder/home
fi
ff=/data/data/com.termux/files
bin=$PREFIX/bin/starttermux
comment "writing launch script"
command="proot"
#command+=" --link2symlink"
#command+=" -0"
command+=" -r $HOME/termux"
command+=" -b /system"
command+=" -b /dev/"
command+=" -b /sys/"
command+=" -b /etc/"
command+=" -b /proc/"
command+=" -b /data/data/com.termux/files/home/drive"
command+=" -w /data/data/com.termux/files/home/"

command+=" $ff/usr/bin/env -i"
command+=" HOME=$ff/home"
command+=" PATH=$ff/usr/bin:$ff/usr/bin/applets"
command+=" TERM=\$TERM"
command+=" ANDROID_DATA=/data"
command+=" ANDROID_ROOT=/system"
command+=" EXTERNAL_STORAGE=/sdcard"
command+=" LANG=\$LANG"
command+=" LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib"
command+=" PREFIX=/data/data/com.termux/files/usr"
cat > $bin <<- EOM
#!/bin/bash
export PROOT_NO_SECCOMP=1
com="\$@"
if [ -L "$folder/home/.termux/shell" ];then
    shell=$ff/home/.termux/shell
    shellname=\`basename \$(readlink $folder/home/.termux/shell)\`
else
    shell=$ff/usr/bin/bash
    shellname=bash
fi
if [ -z "\$1" ];then
    exec $command bash -c "exec -a -\$shellname \$shell"
else
    $command sh -c "\$com"
fi
EOM
comment "fixing shebang of $bin"
termux-fix-shebang $bin
comment "making $bin executable"
chmod +x $bin
